CREATE TABLE productos (
    id INT PRIMARY KEY,
    nombre VARCHAR(100),
    descripcion TEXT,
    precio FLOAT,
    categoria VARCHAR(50)
);

INSERT INTO productos VALUES
(1, 'Oso de Peluche Classic', 'Oso de peluche suave y abrazable de 30cm', 249.99, 'Peluches'),
(2, 'LEGO City Police', 'Set de construcción de estación de policía', 899.99, 'Construcción'),
(3, 'Barbie Fashionista', 'Muñeca Barbie con conjunto moderno', 299.99, 'Muñecas'),
(4, 'Hot Wheels Pack 5', 'Set de 5 carritos Hot Wheels diferentes', 129.99, 'Vehículos'),
(5, 'Pelota Anti-estrés', 'Pelota sensorial con texturas', 49.99, 'Educativos'),
(6, 'Monopoly Clásico', 'Juego de mesa familiar Monopoly', 499.99, 'Juegos de Mesa'),
(7, 'Plastilina Pack', 'Set de 10 colores de plastilina', 79.99, 'Arte'),
(8, 'Dinosaurio T-Rex', 'Figura articulada de dinosaurio', 199.99, 'Figuras de Acción'),
(9, 'Rompecabezas 1000', 'Puzzle de 1000 piezas paisaje', 299.99, 'Puzzles'),
(10, 'Carro RC Veloz', 'Carro control remoto todoterreno', 599.99, 'Control Remoto'),
(11, 'Set Doctor Infantil', 'Kit de doctor con accesorios', 149.99, 'Rol'),
(12, 'Guitarra Musical', 'Guitarra de juguete con sonidos', 179.99, 'Musicales'),
(13, 'Robot Interactivo', 'Robot que baila y habla', 399.99, 'Electrónicos'),
(14, 'Cocina Infantil', 'Set de cocina con accesorios', 699.99, 'Rol'),
(15, 'Pelota Fútbol', 'Pelota de fútbol tamaño 4', 129.99, 'Deportes'),
(16, 'Unicornio Brillante', 'Peluche de unicornio con luces', 279.99, 'Peluches'),
(17, 'Play-Doh Pack', 'Set de 8 botes Play-Doh', 199.99, 'Arte'),
(18, 'Pista Hot Wheels', 'Pista de carreras con loop', 449.99, 'Vehículos'),
(19, 'Bebé Llorones', 'Muñeca que llora lágrimas reales', 449.99, 'Muñecas'),
(20, 'Jenga XXL', 'Jenga tamaño gigante', 399.99, 'Juegos de Mesa'),
(21, 'Set Superhéroes', 'Pack 4 figuras superhéroes', 299.99, 'Figuras de Acción'),
(22, 'Xilófono Colorido', 'Xilófono infantil 8 notas', 149.99, 'Musicales'),
(23, 'Drone Mini', 'Mini drone para principiantes', 799.99, 'Control Remoto'),
(24, 'Caja Herramientas', 'Set herramientas de juguete', 169.99, 'Rol'),
(25, 'Tablero Magnético', 'Pizarra magnética con letras', 199.99, 'Educativos'),
(26, 'Peluche Pokémon', 'Pikachu de peluche 25cm', 249.99, 'Peluches'),
(27, 'LEGO Friends', 'Casa de muñecas LEGO', 799.99, 'Construcción'),
(28, 'Carro Bomberos', 'Camión bomberos con sonidos', 349.99, 'Vehículos'),
(29, 'UNO Cartas', 'Juego de cartas UNO familiar', 119.99, 'Juegos de Mesa'),
(30, 'Kit Científico', 'Set experimentos básicos', 299.99, 'Educativos');